name: SAPO BACKUP SYNC

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - run: pip install requests

      - run: python sync_backup.py
        env:
          LARK_APP_ID: ${{ secrets.LARK_APP_ID }}
          LARK_APP_SECRET: ${{secrets.LARK_APP_SECRET }}
          BASE_TOKEN: ${{ secrets.BASE_TOKEN }}
          SAPO_STORE: ${{ secrets.SAPO_STORE }}
          SAPO_KEY: ${{ secrets.SAPO_SECRET }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
